// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0EHNzKFb78exD81IvfpSID1ejq68LMU',
    appId: '1:339800563796:web:614e68583da1283c188dc1',
    messagingSenderId: '339800563796',
    projectId: 'bsm-manager',
    authDomain: 'bsm-manager.firebaseapp.com',
    storageBucket: 'bsm-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYje9DgEpK-7lkf-17Q1_Da42rgiQnGmM',
    appId: '1:339800563796:android:14b29b77cff53083188dc1',
    messagingSenderId: '339800563796',
    projectId: 'bsm-manager',
    storageBucket: 'bsm-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTN7T6Xb9KjE7uSUO3YxezsooxrKY6jQ',
    appId: '1:339800563796:ios:a9a3f9d7079426f8188dc1',
    messagingSenderId: '339800563796',
    projectId: 'bsm-manager',
    storageBucket: 'bsm-manager.firebasestorage.app',
    androidClientId: '339800563796-lscfnakeaaid3liroh8jkctp0f9isd82.apps.googleusercontent.com',
    iosClientId: '339800563796-dojqltssbni61ff71ne89vhq3b0017jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.lehoainam2224802010139Lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTN7T6Xb9KjE7uSUO3YxezsooxrKY6jQ',
    appId: '1:339800563796:ios:a9a3f9d7079426f8188dc1',
    messagingSenderId: '339800563796',
    projectId: 'bsm-manager',
    storageBucket: 'bsm-manager.firebasestorage.app',
    androidClientId: '339800563796-lscfnakeaaid3liroh8jkctp0f9isd82.apps.googleusercontent.com',
    iosClientId: '339800563796-dojqltssbni61ff71ne89vhq3b0017jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.lehoainam2224802010139Lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk0EHNzKFb78exD81IvfpSID1ejq68LMU',
    appId: '1:339800563796:web:8d4777141022d8c7188dc1',
    messagingSenderId: '339800563796',
    projectId: 'bsm-manager',
    authDomain: 'bsm-manager.firebaseapp.com',
    storageBucket: 'bsm-manager.firebasestorage.app',
  );

}